name: photo_editor_pro
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASIC
  nb_utils: ^6.1.2
  cupertino_icons: ^1.0.6

  #FIREBASE
  firebase_crashlytics: ^3.4.14
  firebase_core: ^2.25.5

  #ADMOB
  google_mobile_ads: ^4.0.0
  facebook_audience_network: ^1.0.1

  #STATE MANAGEMENT
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  device_info_plus: ^9.1.2

  #PERMISSION_HANDLER
  permission_handler: ^11.3.0

  #CONNECTIVITY
  connectivity_plus: ^5.0.2

  #IMAGE_SAVER
  image_gallery_saver: ^4.1.7

  #OTHER
  image: ^4.1.7
  google_fonts: 6.1.0
  url_launcher: ^6.2.4
  share: ^2.0.4
  package_info: ^2.0.2
  #  cached_network_image: ^3.2.3
  http: ^1.2.0
  glass_kit: ^3.0.0
  path_provider: ^2.1.2
  zoom_widget: ^2.0.1
  screenshot: ^2.1.0
  photo_view: ^0.14.0
  flutter_image_compress: ^2.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  video_trimmer: ^3.0.1
  font_awesome_flutter: ^10.7.0
  flutter_vector_icons: ^2.0.0
  flutter_native_image: ^0.0.6+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  image_gallery_saver: ^2.0.3


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/frame/
    - images/stickers/
    - assets/fonts/
    - images/collegeMaker/
    - images/text_box/

  fonts:
    - family: Neon
      fonts:
        - asset: assets/fonts/neon.ttf
    - family: NeonCity
      fonts:
        - asset: assets/fonts/neoncity.otf
    - family: NeonLights
      fonts:
        - asset: assets/fonts/neonlights.ttf